directories:
  output: dist-electron
  buildResources: build
appId: com.example.passworld
productName: PassWorld
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - node_modules/**/*
      - package.json
win:
  target: nsis
  icon: public/icon.ico
mac:
  target: dmg
  icon: public/icon.icns
linux:
  target: AppImage
  icon: public/icon.png
electronVersion: 39.2.7
